behaviors:
    AgenteCarro:
        trainer_type: ppo
        hyperparameters: 
            batch_size: 1040
            buffer_size: 10240
            learning_rate: 5.0e-4
            beta: 5.0e-3
            epsilon: 0.5
            lambd: 0.95
            num_epoch: 3
            learning_rate_schedule: linear
        network_settings:
            normalize: true
            hidden_units: 128
            num_layers: 2
        reward_signals:
            extrinsic: 
                strength: 1
                gamma: 0.99
        max_steps: 10000000
        time_horizon: 64
        summary_freq: 20000
        keep_checkpoints: 5
        checkpoint_interval: 100000
        threaded: true
environment_parameters:
    # 0 = false, 1 = true
    randomBox: 0
    randomCube: 0
    grabBoxCurriculum: 0
    # Recompensas de las diferentes acciones
    rewardGrip: 2
    rewardReleaseInArea: 1
    rewardFinish: 4
    rewardCubeKnockedOff: -1
    rewardCubeReleased: -1
    rewardTime: -1