behaviors:
    TouchCubeMoveGail:
        trainer_type: sac
        hyperparameters: 
            batch_size: 128
            buffer_size: 50000
            learning_rate_schedule: constant
            learning_rate: 3.0e-4
            buffer_init_steps: 0
            tau: 0.005
            steps_per_update: 10
            init_entcoef: 1
            reward_signal_steps_per_update: 10
        network_settings:
            normalize: false
            hidden_units: 128
            num_layers: 2
        reward_signals:
            extrinsic: 
                strength: 1
                gamma: 0.99
        #    gail:
        #        strength: 0.2
        #        gamma: 0.99
        #        encoding_size: 128
        #        learning_rate: 3.0e-4
        #        use_actions: false
        #        use_vail: false
        #        demo_path: Demos/PincherDemoD.demo
        #behavioral_cloning:
        #    strength: 0.5
        #    demo_path: Demos/PincherDemoD.demo
        max_steps: 10000000
        time_horizon: 64
        summary_freq: 10000
        keep_checkpoints: 5
        checkpoint_interval: 500000
        threaded: false
        
